---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-demo-app
  namespace: snyk
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: snyk-demo-app
  template:
    metadata:
      labels:
        app: snyk-demo-app
    spec:
      containers:
        - image: andrestollatscs/snykdemowebapp:latest
          name: snyk-demo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: "DOCKER"
              value: "1"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: snyk-demo-app
  namespace: snyk
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: snyk-demo-app
  type: LoadBalancer
